backend:
  name: github
  repo: poshea48/portfolio
media_folder: static/assets
public_folder: assets
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: blog
    label: Blog
    slug: "{{slug}}-{{month}}-{{year}}"
    folder: src/content/markdown/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
